eventex/core/urls.py
from django.urls import include, path
from eventex.core.views import home, bubble, sendemail


app_name = 'core'


urlpatterns = [
    path('', home, name='home'),
    path('bubble/', bubble, name='bubble'),
    path('email/', sendemail, name='sendemail'),
]

eventex/subscriptions/urls.py
from django.urls import path
import eventex.subscriptions.views as s


app_name = 'subscriptions'


urlpatterns = [
    path('', s.new, name='new'),
    path('<int:pk>/', s.detail, name='detail'),
    path('json/donut/', s.paid_list_json, name='paid_list_json'),
    path('json/column/', s.paid_column_json, name='paid_column_json'),
    path('graphic/', s.graphic, name='graphic'),
]

eventex/urls.py
from django.urls import include, path
from django.contrib import admin

from eventex.core.views import speaker_detail, talk_list

urlpatterns = [
    path('', include('eventex.core.urls', namespace='core')),
    path('inscricao/', include('eventex.subscriptions.urls', namespace='subscriptions')),
    path('palestras/', talk_list, name='talk_list'),
    path('palestrantes/<slug>/', speaker_detail, name='speaker_detail'),
    path('admin/', admin.site.urls),
]

eventex/subscriptions/models.py
from django.db import models
from django.shortcuts import resolve_url as r
from eventex.subscriptions.validators import validate_cpf


class Subscription(models.Model):
    name = models.CharField('nome', max_length=100)
    cpf = models.CharField('CPF', max_length=11, validators=[validate_cpf])
    email = models.EmailField('e-mail', blank=True)
    phone = models.CharField('telefone', max_length=20, blank=True)
    paid = models.BooleanField('pago', default=False)
    created_at = models.DateTimeField('criado em', auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)
        verbose_name = 'inscrição'
        verbose_name_plural = 'inscrições'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return r('subscriptions:detail', self.pk)

eventex/subscriptions/forms.py
from django import forms
from django.core.exceptions import ValidationError
from localflavor.br.forms import BRCPFField
from eventex.subscriptions.models import Subscription
from eventex.subscriptions.validators import validate_cpf


class SubscriptionForm(forms.ModelForm):
    cpf = BRCPFField(label='CPF', max_length=15)

    class Meta:
        model = Subscription
        fields = ['name', 'cpf', 'email', 'phone']

    def clean_name(self):
        name = self.cleaned_data['name']
        prepositions = ['da', 'de', 'di', 'do', 'du']
        words = list(map(lambda w: w.capitalize()
                         if not w in prepositions else w, name.split()))
        return ' '.join(words)

    def clean_cpf(self):
        return self.cleaned_data['cpf'].replace('.', '').replace('-', '') if self.cleaned_data['cpf'] else self.cleaned_data['cpf']

    def clean(self):
        self.cleaned_data = super().clean()

        if not self.cleaned_data.get('email') and not self.cleaned_data.get('phone'):
            raise ValidationError('Informe seu e-mail ou telefone.')

        return self.cleaned_data

eventex/subscriptions/views.py
import json
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.views.generic import DetailView
from eventex.subscriptions.forms import SubscriptionForm
from eventex.subscriptions.mixins import EmailCreateView
from eventex.subscriptions.models import Subscription


new = EmailCreateView.as_view(model=Subscription,
                              form_class=SubscriptionForm,
                              email_subject='Confirmação de inscrição')

detail = DetailView.as_view(model=Subscription)


def count_paid(paid=True):
    return Subscription.objects.filter(paid=paid).count()


def get_data(paid_yes, paid_no):
    data = [{'label': 'Sim', 'value': paid_yes},
            {'label': 'Não', 'value': paid_no},
            ]
    return data


def paid_list_json(request):
    ''' JSON used to generate the graphic '''
    ''' Percent of paid '''
    paid = count_paid()
    total = Subscription.objects.count()
    paid_yes = int(paid * 100 / total)
    paid_no = 100 - paid_yes
    resp = JsonResponse(get_data(paid_yes, paid_no), safe=False)
    return HttpResponse(resp.content)


def paid_column_json(request):
    ''' JSON used to generate the graphic '''
    ''' Quantity of paid '''
    paid_yes = count_paid()
    paid_no = count_paid(paid=False)
    resp = JsonResponse(get_data(paid_yes, paid_no), safe=False)
    return HttpResponse(resp.content)


@login_required
def graphic(request):
    return render(request, 'subscriptions/graphic.html')

eventex/subscriptions/templates/subscriptions/graphic.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<style>
.graph {min-width: 310px; max-width: 800px; height: 250px; margin: 0 auto}
</style>

<div class="col-lg-6">
  <div class="panel panel-default">
      <div class="panel-heading lead">
          Pagos em %
      </div>
      <div class="panel-body">
          <div id="donutchart" class="graph"></div>
      </div>
  </div>
</div>
<div class="col-lg-6">
  <div class="panel panel-default">
      <div class="panel-heading lead">
          Pagos em Quantidade
      </div>
      <div class="panel-body">
          <div id="columnchart" class="graph"></div>
      </div>
  </div>
</div>
{% endblock content %}

{% block js %}
  <script src="{% static 'js/graphics/data.js' %}"></script>
  <script src="{% static 'js/graphics/columnchart.js' %}"></script>
{% endblock js %}

eventex/subscriptions/templates/subscriptions/subscription_detail.html
{% extends "base.html" %}
{% load easy_mask %}

{% block content %}
<section>
    <div class="content row padding-bottom-3 desktop-12 container">
        <h2>Obrigado por se inscrever no Eventex!</h2>
        <div>
            <p>Estes foram os dados que você nos forneceu em sua inscrição:</p>

            <ul>
                <li>Nome: {{ subscription.name }}</li>
                <li>CPF: {{ subscription.cpf|cpf }}</li>
                <li>Email: {{ subscription.email }}</li>
                <li>Telefone: {{ subscription.phone }}</li>
            </ul>

            <p>Em até 48 horas úteis, a nossa equipe entrará em contato com você para concluirmos a sua matrícula.</p>

            <p>Equipe <a href="{% url 'core:home' %}">Eventex</a></p>
            
        </div>
    </div>
</section>
{% endblock content %}

eventex/subscriptions/templates/subscriptions/subscription_form.html
{% extends "base.html" %}

{% block content %}
<section>
  <div class="content row padding-bottom-3 desktop-12 container">
    <h2>Formulário de Inscrição</h2>
    <div class="desktop-6">
      <form action="." method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-row label-block input-text">
          <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
          {{ form.name.errors }}
          {{ form.name }}
        </div>
        <div class="form-row label-block input-text">
          <label for="{{ form.cpf.id_for_label }}">{{ form.cpf.label }}</label>
          {{ form.cpf.errors }}
          {{ form.cpf }}
        </div>
        <div class="form-row label-block input-text">
          <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
          {{ form.email.errors }}
          {{ form.email }}
        </div>
        <div class="form-row label-block input-text">
          <label for="{{ form.phone.id_for_label }}">{{ form.phone.label }}</label>
          {{ form.phone.errors }}
          {{ form.phone }}
        </div>
        <button type="submit" id="id_submit" class="btn btn-blue btn-effect" data-toggle="modal" data-target="#myModalMessage">Enviar</button>
      </form>
    </div>
  </div>
</section>

<!-- Modal -->
<div class="modal fade" id="myModalMessage" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" style="color:#333">Eventex</h4>
      </div>
      <div class="modal-body">
        {{ form.non_field_errors }}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<script>
$.fn.capitalize = function () {
  var wordsToIgnore = ["da","de","di","do", "du"],
      minLength = 2;
  function getWords(str) {
    return str.match(/\S+\s*/g);
  }
  this.each(function () {
    var words = getWords(this.value);
    $.each(words,function(i,word) {
      // only continue if word is not in ignore list
      if (wordsToIgnore.indexOf($.trim(word)) == -1 && $.trim(word).length > minLength) {
        words[i] = words[i].charAt(0).toUpperCase() + words[i].slice(1);
      }
    });
    this.value = words.join("");
  });
};

$('#id_name').on('keyup', function () {
  $(this).capitalize();
}).capitalize();
</script>

<script>
$(document).ready(function(){
  $('#id_cpf').mask('000.000.000-00');
});
</script>

<script>
  $(document).ready(function () {
    // Se apresentar a classe errorlist, significa que algum campo estava inválido e uma lista de erros foi renderizada
    if ($('.errorlist').length > 0) {
      $('#myModalMessage').modal('show');
    }
  });
</script>

{% endblock content %}