eventex/core/urls.py
from django.urls import include, path
from eventex.core.views import home, bubble, sendemail


app_name = 'core'


urlpatterns = [
    path('', home, name='home'),
    path('bubble/', bubble, name='bubble'),
    path('email/', sendemail, name='sendemail'),
]

eventex/subscriptions/urls.py
from django.urls import path
import eventex.subscriptions.views as s


app_name = 'subscriptions'


urlpatterns = [
    path('', s.new, name='new'),
    path('<int:pk>/', s.detail, name='detail'),
    path('json/donut/', s.paid_list_json, name='paid_list_json'),
    path('json/column/', s.paid_column_json, name='paid_column_json'),
    path('graphic/', s.graphic, name='graphic'),
]

eventex/urls.py
from django.urls import include, path
from django.contrib import admin

from eventex.core.views import speaker_detail, talk_list

urlpatterns = [
    path('', include('eventex.core.urls', namespace='core')),
    path('inscricao/', include('eventex.subscriptions.urls', namespace='subscriptions')),
    path('palestras/', talk_list, name='talk_list'),
    path('palestrantes/<slug>/', speaker_detail, name='speaker_detail'),
    path('admin/', admin.site.urls),
]

eventex/core/models.py
from django.db import models
from django.shortcuts import resolve_url as r
from eventex.core.managers import KindQuerySet, PeriodManager


class Speaker(models.Model):
    name = models.CharField('nome', max_length=255)
    slug = models.SlugField('slug')
    photo = models.URLField('foto')
    website = models.URLField('website', blank=True)
    description = models.TextField('descrição', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'palestrante'
        verbose_name_plural = 'palestrantes'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return r('speaker_detail', slug=self.slug)


class Contact(models.Model):
    EMAIL = 'E'
    PHONE = 'P'
    KINDS = (
        (EMAIL, 'Email'),
        (PHONE, 'Telefone'),
    )
    speaker = models.ForeignKey(
        'Speaker',
        verbose_name='palestrante',
        on_delete=models.CASCADE,
    )
    kind = models.CharField('tipo', max_length=1, choices=KINDS)
    value = models.CharField('valor', max_length=255)

    objects = KindQuerySet.as_manager()

    class Meta:
        verbose_name = 'contato'
        verbose_name_plural = 'contatos'

    def __str__(self):
        return self.value


class Talk(models.Model):
    title = models.CharField('título', max_length=200)
    start = models.TimeField('início', blank=True, null=True)
    description = models.TextField('descrição', blank=True)
    speakers = models.ManyToManyField(
        'Speaker', verbose_name='palestrantes', blank=True)

    objects = PeriodManager()

    class Meta:
        ordering = ['start']
        verbose_name = 'palestra'
        verbose_name_plural = 'palestras'

    def __str__(self):
        return self.title


class Course(Talk):
    slots = models.IntegerField()

    objects = PeriodManager()

    class Meta:
        verbose_name = 'curso'
        verbose_name_plural = 'cursos'

eventex/core/views.py
from django.views.generic import TemplateView, ListView, DetailView
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from eventex.core.models import Speaker, Talk, Course


home = ListView.as_view(template_name='index.html', model=Speaker)

speaker_detail = DetailView.as_view(model=Speaker)

talk_list = ListView.as_view(model=Talk)

bubble = TemplateView.as_view(template_name='bubble.html')


def subscribe(request):
    if request.method == 'POST':
        from_email = request.POST.get('from_email', '')
        to_email = 'regis.santos.100@gmail.com'
        message = '<html><body><h2>Obrigado por se inscrever no Eventex.</h2><p>Em breve entraremos em contato.</p></body></html>'
        if from_email:
            try:
                # email para mim
                send_mail('Inscrição no Eventex', from_email + ' se inscreveu no Eventex.', from_email,
                          [to_email], fail_silently=False)
                # email para o inscrito
                send_mail('Inscrição no Eventex', message, to_email,
                          [from_email], fail_silently=False, html_message=message)
                print('Email enviado com sucesso.')
            except BadHeaderError:
                return HttpResponse('Cabeçalho inválido.')
            return HttpResponseRedirect('/')
        else:
            return HttpResponse('Certifique-se de todos os campos estão inseridos e válidos.')


def sendemail(request):
    if request.method == 'POST':
        name = request.POST.get('name', '')
        subject = request.POST.get('subject', '')
        from_email = request.POST.get('email', '')
        to_email = 'regis.santos.100@gmail.com'
        message = request.POST.get('message', '')
        html_message_from = '<html><body><p>Mensagem enviada por ' + \
            name + ', ' + from_email + '</p><p>' + message + '</p></body></html>'
        html_message = '<html><body><h2>Você enviou uma mensagem para Eventex.</h2><p><b>Sua Mensagem:</b></p><p>' + \
            message + '</p></br></br><p><b>Resposta:</b></p><p>Bem-vindo ao Eventex. Em breve entraremos em contato.</p></body></html>'
        if subject and message and from_email:
            try:
                # email para mim
                send_mail(subject, message, from_email,
                          [to_email], fail_silently=False, html_message=html_message_from)
                # email para quem enviou a mensagem
                send_mail(subject, message, to_email,
                          [from_email], fail_silently=False, html_message=html_message)
                print('Email enviado com sucesso.')
            except BadHeaderError:
                return HttpResponse('Cabeçalho inválido.')
            return HttpResponseRedirect('/')
        else:
            return HttpResponse('Certifique-se de todos os campos estão inseridos e válidos.')

eventex/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
        <title>
            {% block title %}Eventex - O maior encontro hacker do mundo!{% endblock title %}
        </title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="Eventex - O maior encontro hacker do mundo!">
    <meta name="author" content="wttd">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <!-- bootstrap.min -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/basalstyle/style.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/alert.css' %}">
    <link rel="stylesheet" href="{% static 'css/morris.css' %}">
    <link href='http://fonts.googleapis.com/css?family=Economica:400,700' rel='stylesheet' type='text/css'>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Morris.js -->
    <script src="{% static 'js/raphael-min.js' %}"></script>
    <script src="{% static 'js/morris.js' %}"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <!-- Highcharts.js -->
    <script src="{% static 'js/highcharts.js' %}"></script>
    
	
    </head>

	<body>
        {% include "nav.html" only %}
        {% block content %}{% endblock content %}
        {% block js %}{% endblock js %}
    </body>
</html>

eventex/core/templates/bubble.html
{% load static %}
<!DOCTYPE html>
<meta charset="utf-8">
<body>

    <!-- d3js -->
    <script src="{% static 'js/d3.v3.min.js' %}"></script>

<script>

var maxRadius = 32, // maximum radius of circle
    padding = 1, // padding between circles; also minimum radius
    margin = {top: -maxRadius, right: -maxRadius, bottom: -maxRadius, left: -maxRadius},
    width = 960 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;

var k = 1, // initial number of candidates to consider per circle
    m = 10, // initial number of circles to add per frame
    n = 2500, // remaining number of circles to add
    newCircle = bestCircleGenerator(maxRadius, padding);

var svg = d3.select("body").append("svg")
    .attr("width", width)
    .attr("height", height)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

d3.timer(function() {
  for (var i = 0; i < m && --n >= 0; ++i) {
    var circle = newCircle(k);

    svg.append("circle")
        .attr("cx", circle[0])
        .attr("cy", circle[1])
        .attr("r", 0)
        .style("fill-opacity", (Math.random() + .5) / 2)
      .transition()
        .attr("r", circle[2]);

    // As we add more circles, generate more candidates per circle.
    // Since this takes more effort, gradually reduce circles per frame.
    if (k < 500) k *= 1.01, m *= .998;
  }
  return !n;
});

function bestCircleGenerator(maxRadius, padding) {
  var quadtree = d3.geom.quadtree().extent([[0, 0], [width, height]])([]),
      searchRadius = maxRadius * 2,
      maxRadius2 = maxRadius * maxRadius;

  return function(k) {
    var bestX, bestY, bestDistance = 0;

    for (var i = 0; i < k || bestDistance < padding; ++i) {
      var x = Math.random() * width,
          y = Math.random() * height,
          rx1 = x - searchRadius,
          rx2 = x + searchRadius,
          ry1 = y - searchRadius,
          ry2 = y + searchRadius,
          minDistance = maxRadius; // minimum distance for this candidate

      quadtree.visit(function(quad, x1, y1, x2, y2) {
        if (p = quad.point) {
          var p,
              dx = x - p[0],
              dy = y - p[1],
              d2 = dx * dx + dy * dy,
              r2 = p[2] * p[2];
          if (d2 < r2) return minDistance = 0, true; // within a circle
          var d = Math.sqrt(d2) - p[2];
          if (d < minDistance) minDistance = d;
        }
        return !minDistance || x1 > rx2 || x2 < rx1 || y1 > ry2 || y2 < ry1; // or outside search radius
      });

      if (minDistance > bestDistance) bestX = x, bestY = y, bestDistance = minDistance;
    }

    var best = [bestX, bestY, bestDistance - padding];
    quadtree.add(best);
    return best;
  };
}

</script>

eventex/core/templates/index_counter.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

    <title>Eventex</title>

    <!-- bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/soon.css' %}">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="assets/js/html5shiv.js"></script>
      <script src="assets/js/respond.min.js"></script>
    <![endif]-->
    
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>

  </head>
  <!-- START BODY -->
  <body class="nomobile">

    <!-- START HEADER -->
    <section id="header">
        <div class="container">
            <header>
                <!-- HEADLINE -->
                <h1 data-animated="GoIn"><b>CONTANDO</b> Eventex em breve...</h1>
            </header>
            <!-- START TIMER -->
            <div id="timer" data-animated="FadeIn">
                <p id="message"></p>
                <div id="days" class="timer_box"></div>
                <div id="hours" class="timer_box"></div>
                <div id="minutes" class="timer_box"></div>
                <div id="seconds" class="timer_box"></div>
            </div>
            <!-- END TIMER -->
            <div class="col-lg-4 col-lg-offset-4 mt centered">
            	<h4>Avise-me quando estiver pronto</h4>
				<form class="form-inline" role="form">
				  <div class="form-group">
				    <label class="sr-only" for="exampleInputEmail2">Email address</label>
				    <input type="email" class="form-control" style="color:#333" id="exampleInputEmail2" placeholder="E-mail">
          </div>
          <!-- Button trigger modal -->
          <button id="submit" type="submit" class="btn btn-info" data-toggle="modal" data-target="#myModal">Enviar</button>
        </form>
      </div>

        </div>
        <!-- LAYER OVER THE SLIDER TO MAKE THE WHITE TEXTE READABLE -->
        <div id="layer"></div>
        <!-- END LAYER -->
        <!-- START SLIDER -->
        <div id="slider" class="rev_slider">
            <ul>
              <li data-transition="slideleft" data-slotamount="1" data-thumb="{% static 'img/slider/banner.jpg' %}">
                <img src="{% static 'img/slider/banner.jpg' %}">
              </li>
              <li data-transition="slideleft" data-slotamount="1" data-thumb="{% static 'img/slider/conference1.jpg' %}">
                <img src="{% static 'img/slider/conference1.jpg' %}">
              </li>
              <li data-transition="slideleft" data-slotamount="1" data-thumb="{% static 'img/slider/conference6.jpg' %}">
                <img src="{% static 'img/slider/conference6.jpg' %}">
              </li>
            </ul>
        </div>
        <!-- END SLIDER -->
    </section>
    <!-- END HEADER -->

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" style="color:#333">Eventex</h4>
          </div>
          <div class="modal-body">
            <p>O e-mail não está funcionando ainda! Desculpe.</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          </div>
        </div>
      </div>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
  	<script type="text/javascript" src="{% static 'js/modernizr.custom.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/soon/plugins.js' %}"></script>
    <script src="{% static 'js/soon/jquery.themepunch.revolution.min.js' %}"></script>
    <script src="{% static 'js/soon/custom.js' %}"></script>

    <script type="text/javascript">
      $('#submit').click(function (e) {
        e.preventDefault();
        // alert("Não está funcionando ainda! Desculpe.");
      });
    </script>
  </body>
  <!-- END BODY -->
</html>

eventex/core/templates/index_eventex.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
        <title>Eventex - O maior encontro hacker do mundo!</title>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="description" content="Eventex - O maior encontro hacker do mundo!">
        <meta name="author" content="wttd">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/basalstyle/style.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

        <link href='http://fonts.googleapis.com/css?family=Economica:400,700' rel='stylesheet' type='text/css'>

        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>


        <script src="{% static 'js/jquery-1.11.0.min.js' %}"></script>
        <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
        <script src="{% static 'js/smooth-scroll.js' %}"></script>
        <script src="{% static 'js/retina-1.1.0.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>


	</head>

	<body>

        <div class="header-frame header-frame-absolute  row">
            <header class="header header-inline min-h-3 row desktop-12 container" role="banner">

                <div class="site-logo">
                    <h1><a href="/" rel="home">Eventex</a></h1>
                    <p class="site-description screen-reader-only">O maior encontro hacker do mundo!</p>
                </div>

                <nav class="nav-inline" role="navigation">
                    <a href="javascript:void(0);" class="nav-mobile"><i class="fa fa-bars"></i></a>
                    <ul>
                        <li><a data-scroll href="#overview">Conferência</a></li>
                        <li><a data-scroll href="#sponsors">Patrocinadores</a></li>
                        <li><a data-scroll href="#register">Inscrição</a></li>
                        <li><a data-scroll href="#venue">Local</a></li>
                    </ul>
                </nav>

            </header>
        </div>

      	<!-- TOP -->
        <section id="top" data-stellar-background-ratio="0.5">
        	<div class="countdown text-align-center row desktop-12 container">
            	<h1 class="uppercase">Eventex</h1>
                <h3>Brasil</h3>
            </div>
        </section>

        <!-- OVERVIEW -->
        <section id="overview">
        	<div class="overview text-align-center row desktop-12 min-h-15 padding-top-2 container">
            	<i class="fa fa-5x fa-globe"></i>
            	<h2>A Conferência</h2>
                <p class="lead">A maior reunião de hackers do mundo.<br>Reunindo profissionais e entusiastas dos quatro <br>cantos do planeta, o <em>Eventex</em> é o lugar onde você precisa estar.</p>
            	<p><a class="btn-basic btn-blue" data-scroll href="#register">Garanta a sua vaga!</a></p>
            </div>
        </section>

        <!-- SPONSORS -->
        <section id="sponsors">
        	<div class="sponsors text-align-center row desktop-12 min-h-28 padding-bottom-2 container">

                <h2>Patrocinadores</h2>

                <h3>Gold</h3>
                <div class="sponsor-slider min-h-6">
                    <img class="img-responsive" src="{% static 'img/sponsor-gold-01.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-gold-02.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-gold-03.png' %}" alt="logo">

                </div>

                <h3>Silver</h3>
                <div class="sponsor-slider min-h-6 margin-bottom-1">
                	<img class="img-responsive" src="{% static 'img/sponsor-silver-01.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-silver-02.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-silver-03.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-silver-04.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-silver-05.png' %}" alt="logo">
                    <img class="img-responsive" src="{% static 'img/sponsor-silver-06.png' %}" alt="logo">
                </div>

                <h3>Seja um patrocinador</h3>
                <p>Interessado? Descubra as oportunidades e benefícios.</p>
                <a class="btn-basic btn-blue" href="mailto:contato@eventex.com.br?Subject=Patrocínio">informe-se</a>

            </div>
        </section>

        <!-- REGISTER -->
        <section id="register">
            <div class="register row">
                <div class="text-align-center row desktop-12 padding-top-2 min-h-14 container">
                	<h2>Inscrição</h2>
                	<h3>Inscrições em breve!</h3>
                    <p>Fique à vontade para entrar em contato com a gente.<br>Teremos prazer em responder quaisquer dúvidas.</p>
                	<a class="btn-basic btn-blue" href="mailto:contato@eventex.com.br">contato@eventex.com.br</a>
                </div>
            </div>
        </section>

        <!-- VENUE -->
        <section id="venue">
            <div class="row min-h-10">

                <div id="map-canvas"></div>
                <div class="row desktop-12 container">
                    <div class="venue row">
                        <div class="venue-address desktop-4 gutter">
                            <h2>Bar Samba Caffé</h2>
                            <p>Melhor que qualquer centro de convenções.</p>
                            <p class="address">
                                <i class="fa fa-2x fa-map-marker fa-inverse"></i>
                                Rua do Ouvidor 23, Centro<br>
                                Rio de Janeiro, RJ
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </body>
</html>

eventex/core/templates/nav.html
<div class="header-frame row">
    <header class="header header-inline min-h-3 row desktop-12 container" role="banner">

        <div class="site-logo">
            <h1><a href="{% url 'core:home' %}" rel="home">Eventex</h1>
            <p class="site-description screen-reader-only">O maior encontro hacker do mundo!</p>
        </div>

        <nav class="nav-inline" role="navigation">
            <a href="javascript:void(0);" class="nav-mobile"><i class="fa fa-bars"></i></a>
            <ul>
                <li><a data-scroll href="{% url 'core:home' %}#about">Conferência</a></li>
                <li><a data-scroll href="{% url 'talk_list' %}">Palestras</a></li>
                <li><a data-scroll href="{% url 'core:home' %}#speakers">Palestrantes</a></li>
                <li><a data-scroll href="{% url 'core:home' %}#sponsor">Patrocinadores</a></li>
                <li><a data-scroll href="{% url 'core:home' %}#contact">Contato</a></li>
                <li><a data-scroll href="{% url 'core:home' %}#google-map">Local</a></li>
                <li><a data-scroll href="{% url 'subscriptions:new' %}">Inscrição</a></li>
            </ul>
        </nav>

    </header>
</div>